### ISSUE TITLE
Can we download all images from a specific collection?

### ISSUE THREAD

**Issue by ericodes** [MehediH/Bulksplash#12]
Would be nice to be able to download curated collections! :)

**Comment by MehediH** [comment]
@ericodes Hey! Thanks for the idea -- I'm implementing this feature now, but need some suggestions:

* how would you prefer to input which collection to download? just the URL (e.g. https://unsplash.com/collections/206/makers%3A-cat-and-ben)? 
* instead of downloading all images, wouldn't it be better to let the user decide how many images they want to download?

Please let me know if you see this :)

**Comment by MehediH** [comment]
Implemented in v2
