### ISSUE TITLE
İts not working

### ISSUE THREAD

**Issue by ky456** [MehediH/Bulksplash#30]
Something went wrong, got response code 403 from Unsplash - Forbidden

**Comment by jwblangley** [comment]
I've had this also. Appears to only occur when you opt out of downloading the JSON of authors etc. My guess is that this is due to  Unsplash API policy not (potentially no longer) permitting downloads without display of accreditation. https://help.unsplash.com/en/articles/2511245-unsplash-api-guidelines

**Comment by MehediH** [comment]
This should be fixed now but you need your own API key now
